name: "Terraform CI/CD DEV"

on:
  pull_request_target:
    branches:
      - dev

  push:
    branches:
      - dev

permissions:
      id-token: write
      contents: read

env:
  AWS_REGION: eu-central-1
  ENVIRONMENT: dev
  BUCKET_STATE: lapaya-stepan-dev-tfstate
  BUCKET_KEY: dev.state

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.8

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE }}

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="bucket=${{ env.BUCKET_STATE }}" -backend-config="key=${{ env.BUCKET_KEY }}" -reconfigure

      - name: Terraform Plan
        id: plan
        run: terraform plan -var env=${{ env.ENVIRONMENT }} -lock-timeout=600s

      - name: Terraform Apply
        id: apply
        run: terraform apply -var env=${{ env.ENVIRONMENT }} -auto-approve -lock-timeout=600s
